config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#index'

  resources :dashboard, only: [:show] do
    member do
      get 'preview/:mode', to: 'dashboard#preview', as: 'preview'
      get 'show_add_widget/:row_id', to: 'dashboard#show_add_widget', as: 'show_add_widget'
      put :increase_version
    end

    resources :widgets, only: [:create, :update, :destroy] do
      member do
        post 'wrap'
        post 'unwrap'
        patch 'update_position'
        get 'show_settings'
        patch 'update_settings'
      end
    end
  end

end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
  has_many :widgets
  belongs_to :user

  before_create :add_widget

private

  def add_widget
    widgets << Widget.create!(widget_type: 'ROW', position: 0)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  has_one :dashboard

  before_create :add_dashboard

private

  def add_dashboard
    self.dashboard = Dashboard.create!
  end

end

app/models/widget.rb
class Widget < ActiveRecord::Base
  WIDGET_TYPES = %w(ROW WEATHER TIME_AND_DATE COUNTDOWN QUOTE CUSTOM_HTML NY_TIMES DIRECTIONS RSS)

  belongs_to :dashboard
  belongs_to :parent, foreign_key: :parent_id, class_name: :Widget
  has_many :children, foreign_key: :parent_id, class_name: :Widget

  validates_presence_of :widget_type, :position
  validates_inclusion_of :widget_type, in: WIDGET_TYPES

  after_initialize do |widget|
    widget.settings = {} if widget.new_record?
  end

  store_accessor :settings,
                 :location_full_name, :location_lat, :location_lon, :location_name, # WEATHER
                 :time_zone, :time_zone_label, # TIME AND DATE
                 :countdown_label, :countdown_date_time, # COUNTDOWN
                 :custom_html, :custom_css, # CUSTOM HTML
                 :ny_times_category, :ny_times_limit, # NY TIMES
                 :directions_from, :directions_to, :directions_from_short_name, :directions_to_short_name, :directions_mode, # DIRECTIONS
                 :rss_url, :rss_limit # RSS

  def self.by_position
    order(position: :asc)
  end

  def self.all_types
    WIDGET_TYPES
  end

  def self.widget_types
    WIDGET_TYPES.reject { |wt| wt == "ROW" }
  end

  def insert_new_row(position)
    children.where('position >= ?', position).each do |child|
      child.update(position: child.position + 1)
    end
    Widget.create!(widget_type: "ROW", position: position, parent_id: id)
  end

  def top?
    parent_id.nil?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate!
    unless user_signed_in?
      redirect_to new_user_session_path
    end
  end

  def after_sign_in_path_for(resource)
    user = resource
    dashboard_path(user.dashboard)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  before_action :authenticate!

  def show
    @dashboard = Dashboard.find(params[:id])
    respond_to do |f|
      f.html
      f.json { render json: { version: @dashboard.version }.to_json }
    end
  end

  def increase_version
    @dashboard = Dashboard.find(params[:id])
    version = @dashboard.version || 0
    @dashboard.update(version: version + 1)
    redirect_to @dashboard
  end

  def preview
    @dashboard = Dashboard.find(params[:id])
    @mode = params[:mode]
    render 'preview', layout: 'preview'
  end

  def show_add_widget
    @dashboard = Dashboard.find(params[:id])
    @row = Widget.find(params[:row_id])
    render 'add_widget', layout: false
  end

private

  def widget_params
    params.require(:dashboard).permit(:version)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController

  before_action :authenticate!

  def create
    @dashboard = Dashboard.find(params[:dashboard_id])
    widget = Widget.create!(widget_params)
    if widget.parent.present?
      widget.parent.children << widget
      render partial: 'dashboard/widget', locals: { widget: widget }
    else
      @dashboard.widgets << widget
      render partial: 'dashboard/row', locals: { widget: widget }
    end
  end

  def update
    Widget.find(params[:id]).update(widget_params)
    head :ok, content_type: 'text/html'
  end

  def update_position
    widget = Widget.find(params[:id])
    widget.update(widget_params)
    row = Widget.find(widget.parent)
    row.children.where('position >= ? and id != ?', widget_params[:position], params[:id]).each do |child|
      child.update(position: child.position + 1)
    end
    head :ok, content_type: 'text/html'
  end

  def wrap
    @dashboard = Dashboard.find(params[:dashboard_id])
    widget = Widget.find(params[:id])
    current_parent = widget.parent
    current_parent.children.delete(widget)
    new_row_right = current_parent.insert_new_row(widget_wrap_params[:current_position])
    new_row_left = current_parent.insert_new_row(widget_wrap_params[:current_position])
    if widget_wrap_params[:move_direction] == 'left'
      new_row_left.children << widget
    else
      new_row_right.children << widget
    end

    render partial: 'dashboard/element', locals: { widget: current_parent }
  end

  def unwrap
    widget = Widget.find(params[:id])
    current_parent = widget.parent
    new_parent = current_parent.parent
    if widget_wrap_params[:move_direction] == 'left'
      new_parent.children.where(position: current_parent.position - 1).first.destroy!
    else
      new_parent.children.where(position: current_parent.position + 1).first.destroy!
    end
    widget.update(parent: new_parent)
    current_parent.destroy!

    head :ok, content_type: 'text/html'
  end

  def destroy
    Widget.find(params[:id]).destroy!
    head :ok, content_type: 'text/html'
  end

  def show_settings
    @dashboard = Dashboard.find(params[:dashboard_id])
    @widget = Widget.find(params[:id])
    render 'settings', layout: false
  end

  def update_settings
    widget = Widget.find(params[:id])
    widget.update!(widget_settings_params)
    head :ok, content_type: 'text/html'
  end

private

  def widget_params
    params.require(:widget).permit(:widget_type, :position, :parent_id)
  end

  def widget_settings_params
    params.require(:widget).permit(:settings,
                                   :location_full_name, :location_name, :location_lat, :location_lon,
                                   :time_zone, :time_zone_label,
                                   :countdown_label, :countdown_date_time,
                                   :custom_html, :custom_css,
                                   :ny_times_category, :ny_times_limit,
                                   :directions_from, :directions_to, :directions_from_short_name, :directions_to_short_name, :directions_mode,
                                   :rss_url, :rss_limit)
  end

  def widget_wrap_params
    params.require(:widget).permit(:move_direction, :current_position)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
require 'rss'

module DashboardHelper

  def read_rss(widget)
    if widget.rss_url
      RSS::Parser.parse(open(widget.rss_url).read, false).items[0..widget.rss_limit.to_i]
    end
  rescue StandardError => error
    puts error.message
  end

end

app/helpers/widgets_helper.rb
module WidgetsHelper

  def time_zone_options
    ActiveSupport::TimeZone.all.map do |time_zone|
      utc_offset = ActiveSupport::TimeZone.seconds_to_utc_offset(time_zone.utc_offset)
      time_zone_name = ActiveSupport::TimeZone::MAPPING[time_zone.name]

      ["(GMT#{utc_offset}) #{time_zone_name}", time_zone_name]
    end
  end

  def directions_mode_list
    [['driving', 'google.maps.TravelMode.DRIVING'], ['bicycling', 'google.maps.TravelMode.BICYCLING'],
     ['transit', 'google.maps.TravelMode.TRANSIT'], ['walking', 'google.maps.TravelMode.WALKING']]
  end

end

app/views/dashboard/_element.html.slim
- if widget.widget_type == "ROW"
  = render 'dashboard/row', widget: widget
- else
  = render 'dashboard/widget', widget: widget

app/views/dashboard/_row.html.slim
- row_class = local_assigns.fetch(:row_class) { '' }
div{class="#{row_class} #{widget.top? ? 'row widget-container container-row' : 'widget-container position-element container-block col-md-6'}"
    data-row-id="#{widget.id}" data-widget-position="#{widget.position}"}
  - widget.children.by_position.each do |child_widget|
    = render 'dashboard/element', widget: child_widget
  a.btn.btn-danger.destroy-widget-button.glyphicon.glyphicon-remove-circle.js-destroy-row-button href="#{dashboard_widget_path(@dashboard.id, widget.id) if widget.id}"
  - if widget.top?
    div.row style="clear: both;"
      a.btn.btn-success.add-widget-button.js-add-widget-button href="#{show_add_widget_dashboard_path(@dashboard.id, widget.id)}" +

app/views/dashboard/_side_panel.html.slim
.side-panel-wrapper
  .side-panel.js-side-panel
    - Widget.widget_types.each do |widget_type|
      = render 'widget', widget: Widget.new(widget_type: widget_type),  widget_class: "sidepanel-widget"

app/views/dashboard/_widget.html.slim
- widget_class = local_assigns.fetch(:widget_class) { '' }
.widget.position-element.col-md-12.pl0.pr0 { class="#{widget_class}" data-widget-type="#{widget.widget_type}" data-widget-position="#{widget.position}"
  data-href="#{widget.id ? dashboard_widget_path(@dashboard.id, widget.id) : dashboard_widgets_path(@dashboard)}" }
  a.left-handle.js-left-widget-handle href="#{dashboard_widget_path(@dashboard.id, widget.id) if widget.id}" &larr;
  .widget-content
    = widget.widget_type.capitalize.humanize
  a.btn.btn-default.widget-settings-btn.widget-btn.glyphicon.glyphicon-wrench.js-widget-settings-btn {
    href="#{show_settings_dashboard_widget_path(@dashboard.id, widget.id) if widget.id}" }
  a.btn.btn-danger.widget-delete-btn.widget-btn.glyphicon.glyphicon-remove-circle.js-widget-delete-btn {
    href="#{dashboard_widget_path(@dashboard.id, widget.id) if widget.id}" }
  a.right-handle.js-right-widget-handle href="#{dashboard_widget_path(@dashboard.id, widget.id) if widget.id}" &rarr;

app/views/dashboard/add_widget.html.slim
.modal-header Add new widget
.modal-body
  - Widget.widget_types.each do |widget_type|
    div.add-widget-row.js-add-widget-row data-widget-type="#{widget_type}" data-row-id="#{@row.id}" data-href="#{dashboard_widgets_path(@dashboard)}"
      = widget_type.capitalize.humanize

app/views/dashboard/index.html.slim
| Dashboard page

app/views/dashboard/preview.html.slim
- content_for :body_class, 'inverted' if @mode == 'inverted'
input.js-dashboard-url type="hidden" value="#{dashboard_path(@dashboard)}"
input.js-dashboard-version type="hidden" value="#{@dashboard.version}"
.containers
  - @dashboard.widgets.by_position.each do |widget|
    = render 'dashboard/preview/element', widget: widget

app/views/dashboard/preview/_countdown.html.slim
.countdown-wrapper
  .countdown-label
  .countdown-date-time

app/views/dashboard/preview/_countdown_settings.html.slim
input.js-countdown-label type="hidden" value="#{widget.countdown_label}"
input.js-countdown-date-time type="hidden" value="#{widget.countdown_date_time}"

app/views/dashboard/preview/_custom_html.html.slim
style
  = widget.custom_css

.custom-html
  = widget.custom_html.html_safe if widget.custom_html

app/views/dashboard/preview/_directions.html.slim
.directions-wrapper
  | It would take you
  .directions-time
  | to get from #{widget.directions_from_short_name} to #{widget.directions_to_short_name}

app/views/dashboard/preview/_directions_settings.html.slim
input.js-directions-from type="hidden" value="#{widget.directions_from}"
input.js-directions-to type="hidden" value="#{widget.directions_to}"
input.js-directions-mode type="hidden" value="#{widget.directions_mode}"

app/views/dashboard/preview/_element.html.slim
- if widget.widget_type == "ROW"
  = render 'dashboard/preview/row', widget: widget
- else
  = render 'dashboard/preview/widget', widget: widget

app/views/dashboard/preview/_ny_times.html.slim
.ny-times-wrapper

app/views/dashboard/preview/_ny_times_settings.html.slim
input.js-ny-times-category type="hidden" value="#{widget.ny_times_category}"
input.js-ny-times-limit type="hidden" value="#{widget.ny_times_limit}"

app/views/dashboard/preview/_quote.html.slim
h1.quote-text.js-quote-text align="center" Quote Here
h2.quote-author.js-quote-author Author Here

app/views/dashboard/preview/_row.html.slim
div class="#{widget.top? ? 'row container container-row' : 'container container-block col-md-6'}"
  - widget.children.by_position.each do |child_widget|
    = render 'dashboard/preview/element', widget: child_widget

app/views/dashboard/preview/_time_and_date.html.slim
.time-and-date-wrapper
  .time-and-date-label
  .time-and-date

app/views/dashboard/preview/_time_and_date_settings.html.slim
input.js-time-zone type="hidden" value="#{widget.time_zone}"
input.js-time-zone-label type="hidden" value="#{widget.time_zone_label}"

app/views/dashboard/preview/_weather_settings.html.slim
input.js-location-full-name type="hidden" value="#{widget.location_full_name}"
input.js-location-name type="hidden" value="#{widget.location_name}"
input.js-location-lat type="hidden" value="#{widget.location_lat}"
input.js-location-lon type="hidden" value="#{widget.location_lon}"

app/views/dashboard/preview/_widget.html.slim
.widget.col-md-12.pl0.pr0 data-widget-type="#{widget.widget_type}"
  .widget-settings
    - if widget.widget_type == "WEATHER"
      = render 'dashboard/preview/weather_settings', widget: widget
    - elsif widget.widget_type == "TIME_AND_DATE"
      = render 'dashboard/preview/time_and_date_settings', widget: widget
    - elsif widget.widget_type == "COUNTDOWN"
      = render 'dashboard/preview/countdown_settings', widget: widget
    - elsif widget.widget_type == "NY_TIMES"
      = render 'dashboard/preview/ny_times_settings', widget: widget
    - elsif widget.widget_type == "DIRECTIONS"
      = render 'dashboard/preview/directions_settings', widget: widget
  .widget-content
    - if widget.widget_type == "QUOTE"
      = render 'dashboard/preview/quote', widget: widget
    - elsif widget.widget_type == "TIME_AND_DATE"
      = render 'dashboard/preview/time_and_date', widget: widget
    - elsif widget.widget_type == "COUNTDOWN"
      = render 'dashboard/preview/countdown', widget: widget
    - elsif widget.widget_type == "CUSTOM_HTML"
      = render 'dashboard/preview/custom_html', widget: widget
    - elsif widget.widget_type == "NY_TIMES"
      = render 'dashboard/preview/ny_times', widget: widget
    - elsif widget.widget_type == "DIRECTIONS"
      = render 'dashboard/preview/directions', widget: widget
    - elsif widget.widget_type == "RSS"
      - items = read_rss(widget)
      .rss-wrapper
        - items && items.each do |item|
          .rss-item
            .rss-item-title = item.title
            .rss-item-description = strip_tags(item.description)

app/views/dashboard/show.html.slim
- content_for :side
  = render 'side_panel'
  a.btn.btn-default.side-btn.js-side-btn Widgets

.row.mb20
  a.btn.btn-success.mr5 target="_blank" href="#{preview_dashboard_path(@dashboard, 'inverted')}" Mirror mode
  = link_to "Save", increase_version_dashboard_path(@dashboard), method: :put, class: 'btn btn-primary mr5'
  span.note * Note: Save will trigger an update on a device

.containers
  - @dashboard.widgets.by_position.each do |widget|
    = render 'element', widget: widget
  .row.last-row
    a.btn.btn-default.js-add-row-button href="#{dashboard_widgets_path(@dashboard)}" Add Row

app/views/layouts/application.html.slim
doctype XML
doctype Strict
html lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml"
  head
    title
      | Project: Mirror
    = stylesheet_link_tag 'application', media: 'all'
    script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAK4rNJ_lAJcldW5JWo2uIqosZX65dmtR4&libraries=places"
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body.navbar-fixed.breadcrumbs-fixed class=(yield :body_class)
    = render 'shared/header'

    = yield :side

    .container
      - flash.each do |key, value|
        div.alert class="#{key == "notice" ? "alert-info" : "alert-danger"}"
          = value

      = yield

    .modal.fade#modal tabindex="-1" role="dialog"
      .modal-dialog
        .modal-content
          h3.modal-header
            button type="button" class="close" data-dismiss="modal" aria-label="Close" &times;
          .modal-body
            p One fine body&hellip;

app/views/layouts/preview.html.slim
doctype XML
doctype Strict
html lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml"
  head
    title
      | Project: Mirror
    = stylesheet_link_tag 'preview', media: 'all'
    = javascript_include_tag 'preview'
    script src="http://maps.google.com/maps/api/js?key=AIzaSyCJmom_RTJvoR7k3t4ymMuIdH2QjZ5lFRQ"
    = csrf_meta_tags
    meta name="viewport" content="width=device-width"
  body.navbar-fixed.breadcrumbs-fixed class=(yield :body_class)
    .container
      = yield

app/views/pages/index.html.slim
- if current_user
  ' Welcome to mirror project
- else
  ' Welcome to mirror project, please log in or sign up to proceed.

app/views/shared/_header.html.slim
nav.navbar.navbar-default
  .navbar-header
    = link_to 'Project: Mirror', root_path, class: 'navbar-brand'
  #navbar
    ul.nav.navbar-nav
      - if user_signed_in?
        li
          = link_to 'Dashboard', dashboard_path(current_user.dashboard)
    ul.nav.navbar-nav.pull-right
      - if user_signed_in?
        li.dropdown
          a.dropdown-toggle data-toggle="dropdown" href="#"
            = current_user.email
            span.caret
          ul.dropdown-menu role="menu"
            li = link_to 'Profile', edit_user_registration_path
            li = link_to 'Log out', destroy_user_session_path, method: :delete
      - else
        li = link_to 'Log In', new_user_session_path
        li = link_to 'Sign Up', new_user_registration_path

app/views/widgets/_countdown_settings.html.slim
h4 Edit #{@widget.widget_type.capitalize} Widget Settings

= form_for(@widget, url: update_settings_dashboard_widget_path(@dashboard, @widget),
           html: {method: :patch, class: 'js-widget-settings-form'}, remote: true) do |f|
  .row
    .col-md-8
      .form-group
        = f.label :countdown_label
        = f.text_field :countdown_label, placeholder: "(optional)", class: 'form-control'
      .form-group
        = f.label :countdown_date_time
        = f.text_field :countdown_date_time, class: 'js-countdown-date-time form-control'

  .actions
    a.btn.btn-default.mr5 data-dismiss="modal" href="#" Cancel
    = f.submit "Save", class: "btn btn-primary"

app/views/widgets/_custom_html_settings.html.slim
h4 Edit #{@widget.widget_type.capitalize.humanize} Widget Settings

= form_for(@widget, url: update_settings_dashboard_widget_path(@dashboard, @widget),
           html: {method: :patch, class: 'js-widget-settings-form'}, remote: true) do |f|
  .row
    .col-md-12
      .form-group
        = f.label :custom_html
        = f.text_area :custom_html, rows: 6, class: 'form-control'
      .form-group
        = f.label :custom_css
        = f.text_area :custom_css, rows: 6, class: 'form-control'

  .actions
    a.btn.btn-default.mr5 data-dismiss="modal" href="#" Cancel
    = f.submit "Save", class: "btn btn-primary"

app/views/widgets/_directions_settings.html.slim
h4 Edit #{@widget.widget_type.capitalize.humanize} Widget Settings

= form_for(@widget, url: update_settings_dashboard_widget_path(@dashboard, @widget),
           html: {method: :patch, class: 'js-widget-settings-form'}, remote: true) do |f|
  .row
    .col-md-8
      .form-group
        = f.label :directions_mode
        = f.select :directions_mode, directions_mode_list, {}, class: 'form-control'
      .form-group
        = f.label :directions_from
        = f.text_field :directions_from, rows: 6, class: 'form-control js-directions-from'
      .form-group
        = f.label :directions_to
        = f.text_field :directions_to, rows: 6, class: 'form-control js-directions-to'

      = f.hidden_field :directions_from_short_name, class: "js-directions-from-short-name"
      = f.hidden_field :directions_to_short_name, class: "js-directions-to-short-name"

  .actions
    a.btn.btn-default.mr5 data-dismiss="modal" href="#" Cancel
    = f.submit "Save", class: "btn btn-primary"

app/views/widgets/_ny_times_settings.html.slim
h4 Edit #{@widget.widget_type.capitalize.humanize} Widget Settings

= form_for(@widget, url: update_settings_dashboard_widget_path(@dashboard, @widget),
           html: {method: :patch, class: 'js-widget-settings-form'}, remote: true) do |f|
  - sections = ['arts', 'automobiles', 'blogs', 'books', 'business', 'education' 'fashion & style', 'food', 'health',
                'home & garden', 'job market', 'movies', 'science', 'sports', 'technology', 'theater',
                'travel', 'u.s.', 'world', 'your money']

  .row
    .col-md-8
      .form-group
        = f.label :ny_times_category
        = f.select :ny_times_category, sections, {}, rows: 6, class: 'form-control'
      .form-group
        = f.label :ny_times_limit
        = f.select :ny_times_limit, %w(3 5 10 20), {}, class: 'form-control'

  .actions
    a.btn.btn-default.mr5 data-dismiss="modal" href="#" Cancel
    = f.submit "Save", class: "btn btn-primary"

app/views/widgets/_rss_settings.html.slim
h4 Edit #{@widget.widget_type.capitalize.humanize} Widget Settings

= form_for(@widget, url: update_settings_dashboard_widget_path(@dashboard, @widget),
           html: {method: :patch, class: 'js-widget-settings-form'}, remote: true) do |f|
  .row
    .col-md-12
      .form-group
        = f.label :rss_url
        = f.text_field :rss_url, class: 'form-control'
      .form-group
        = f.label :rss_limit
        = f.select :rss_limit, %w(3 5 10 20), {}, class: 'form-control'

  .actions
    a.btn.btn-default.mr5 data-dismiss="modal" href="#" Cancel
    = f.submit "Save", class: "btn btn-primary"

app/views/widgets/_time_and_date_settings.html.slim
h4 Edit #{@widget.widget_type.capitalize.humanize} Widget Settings

= form_for(@widget, url: update_settings_dashboard_widget_path(@dashboard, @widget),
           html: {method: :patch, class: 'js-widget-settings-form'}, remote: true) do |f|
  .row
    .col-md-8
      .form-group
        = f.label :time_zone_label
        = f.text_field :time_zone_label, placeholder: "(optional)", class: 'form-control'
      .form-group
        = f.label :time_zone
        = f.select :time_zone, options_for_select(time_zone_options, @widget.time_zone || "-05:00"), {}, class: 'form-control'

  .actions
    a.btn.btn-default.mr5 data-dismiss="modal" href="#" Cancel
    = f.submit "Save", class: "btn btn-primary"

app/views/widgets/_weather_settings.html.slim
h4 Edit #{@widget.widget_type.capitalize} Widget Settings

= form_for(@widget, url: update_settings_dashboard_widget_path(@dashboard, @widget),
           html: {method: :patch, class: 'js-widget-settings-form'}, remote: true) do |f|
  .row
    .col-md-8
      .form-group
        = f.label :location_full_name
        = f.text_field :location_full_name, autofocus: true, class: 'form-control js-weather-location'
        = f.hidden_field :location_lat, class: "js-weather-location-lat"
        = f.hidden_field :location_lon, class: "js-weather-location-lon"
        = f.hidden_field :location_name, class: "js-weather-location-name"

  .actions
    a.btn.btn-default.mr5 data-dismiss="modal" href="#" Cancel
    = f.submit "Save", class: "btn btn-primary"

app/views/widgets/settings.html.slim
.modal-header #{@widget.widget_type.capitalize.humanize} widget settings
.modal-body
  - if @widget.widget_type == "WEATHER"
    = render 'weather_settings'
  - elsif @widget.widget_type == "TIME_AND_DATE"
    = render 'time_and_date_settings'
  - elsif @widget.widget_type == "COUNTDOWN"
    = render 'countdown_settings'
  - elsif @widget.widget_type == "CUSTOM_HTML"
    = render 'custom_html_settings'
  - elsif @widget.widget_type == "NY_TIMES"
    = render 'ny_times_settings'
  - elsif @widget.widget_type == "DIRECTIONS"
    = render 'directions_settings'
  - elsif @widget.widget_type == "RSS"
    = render 'rss_settings'
  - else
    | No settings available.